
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtStudentAward;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "studentExcellAwardServiceService", targetNamespace = "http://www.primeton.com/studentExcellAwardService", wsdlLocation = "http://fwdt.siso.edu.cn/default/studentExcellAwardService?wsdl")
public class StudentExcellAwardServiceService
    extends Service
{

    private final static URL STUDENTEXCELLAWARDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTEXCELLAWARDSERVICESERVICE_EXCEPTION;
    private final static QName STUDENTEXCELLAWARDSERVICESERVICE_QNAME = new QName("http://www.primeton.com/studentExcellAwardService", "studentExcellAwardServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fwdt.siso.edu.cn/default/studentExcellAwardService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTEXCELLAWARDSERVICESERVICE_WSDL_LOCATION = url;
        STUDENTEXCELLAWARDSERVICESERVICE_EXCEPTION = e;
    }

    public StudentExcellAwardServiceService() {
        super(__getWsdlLocation(), STUDENTEXCELLAWARDSERVICESERVICE_QNAME);
    }

    public StudentExcellAwardServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTEXCELLAWARDSERVICESERVICE_QNAME, features);
    }

    public StudentExcellAwardServiceService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTEXCELLAWARDSERVICESERVICE_QNAME);
    }

    public StudentExcellAwardServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTEXCELLAWARDSERVICESERVICE_QNAME, features);
    }

    public StudentExcellAwardServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentExcellAwardServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentExcellAwardService
     */
    @WebEndpoint(name = "studentExcellAwardServicePort")
    public StudentExcellAwardService getStudentExcellAwardServicePort() {
        return super.getPort(new QName("http://www.primeton.com/studentExcellAwardService", "studentExcellAwardServicePort"), StudentExcellAwardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentExcellAwardService
     */
    @WebEndpoint(name = "studentExcellAwardServicePort")
    public StudentExcellAwardService getStudentExcellAwardServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.primeton.com/studentExcellAwardService", "studentExcellAwardServicePort"), StudentExcellAwardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTEXCELLAWARDSERVICESERVICE_EXCEPTION!= null) {
            throw STUDENTEXCELLAWARDSERVICESERVICE_EXCEPTION;
        }
        return STUDENTEXCELLAWARDSERVICESERVICE_WSDL_LOCATION;
    }

}
