
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "punishService", targetNamespace = "http://www.primeton.com/punishService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PunishService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/punishService")
    @RequestWrapper(localName = "queryPunishInfos", targetNamespace = "http://www.primeton.com/punishService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs.QueryPunishInfos")
    @ResponseWrapper(localName = "queryPunishInfosResponse", targetNamespace = "http://www.primeton.com/punishService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs.QueryPunishInfosResponse")
    public String queryPunishInfos();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out1", targetNamespace = "http://www.primeton.com/punishService")
    @RequestWrapper(localName = "queryRePunishApplyInfos", targetNamespace = "http://www.primeton.com/punishService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs.QueryRePunishApplyInfos")
    @ResponseWrapper(localName = "queryRePunishApplyInfosResponse", targetNamespace = "http://www.primeton.com/punishService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs.QueryRePunishApplyInfosResponse")
    public String queryRePunishApplyInfos();

}
