
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtPunishs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "punishServiceService", targetNamespace = "http://www.primeton.com/punishService", wsdlLocation = "http://fwdt.siso.edu.cn/default/punishService?wsdl")
public class PunishServiceService
    extends Service
{

    private final static URL PUNISHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PUNISHSERVICESERVICE_EXCEPTION;
    private final static QName PUNISHSERVICESERVICE_QNAME = new QName("http://www.primeton.com/punishService", "punishServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fwdt.siso.edu.cn/default/punishService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUNISHSERVICESERVICE_WSDL_LOCATION = url;
        PUNISHSERVICESERVICE_EXCEPTION = e;
    }

    public PunishServiceService() {
        super(__getWsdlLocation(), PUNISHSERVICESERVICE_QNAME);
    }

    public PunishServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUNISHSERVICESERVICE_QNAME, features);
    }

    public PunishServiceService(URL wsdlLocation) {
        super(wsdlLocation, PUNISHSERVICESERVICE_QNAME);
    }

    public PunishServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUNISHSERVICESERVICE_QNAME, features);
    }

    public PunishServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PunishServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PunishService
     */
    @WebEndpoint(name = "punishServicePort")
    public PunishService getPunishServicePort() {
        return super.getPort(new QName("http://www.primeton.com/punishService", "punishServicePort"), PunishService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PunishService
     */
    @WebEndpoint(name = "punishServicePort")
    public PunishService getPunishServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.primeton.com/punishService", "punishServicePort"), PunishService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUNISHSERVICESERVICE_EXCEPTION!= null) {
            throw PUNISHSERVICESERVICE_EXCEPTION;
        }
        return PUNISHSERVICESERVICE_WSDL_LOCATION;
    }

}
