
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtWalkSchool;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "walkSchoolInterfaceService", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WalkSchoolInterfaceService {


    /**
     * 
     * @param year
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "walkSchools", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService")
    @RequestWrapper(localName = "queryWalkSchool", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtWalkSchool.QueryWalkSchool")
    @ResponseWrapper(localName = "queryWalkSchoolResponse", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtWalkSchool.QueryWalkSchoolResponse")
    public String queryWalkSchool(
        @WebParam(name = "year", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService")
        String year);

}
