
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtWalkSchool;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "walkSchoolInterfaceServiceService", targetNamespace = "http://www.primeton.com/walkSchoolInterfaceService", wsdlLocation = "http://fwdt.siso.edu.cn/default/walkSchoolInterfaceService?wsdl")
public class WalkSchoolInterfaceServiceService
    extends Service
{

    private final static URL WALKSCHOOLINTERFACESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WALKSCHOOLINTERFACESERVICESERVICE_EXCEPTION;
    private final static QName WALKSCHOOLINTERFACESERVICESERVICE_QNAME = new QName("http://www.primeton.com/walkSchoolInterfaceService", "walkSchoolInterfaceServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fwdt.siso.edu.cn/default/walkSchoolInterfaceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WALKSCHOOLINTERFACESERVICESERVICE_WSDL_LOCATION = url;
        WALKSCHOOLINTERFACESERVICESERVICE_EXCEPTION = e;
    }

    public WalkSchoolInterfaceServiceService() {
        super(__getWsdlLocation(), WALKSCHOOLINTERFACESERVICESERVICE_QNAME);
    }

    public WalkSchoolInterfaceServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WALKSCHOOLINTERFACESERVICESERVICE_QNAME, features);
    }

    public WalkSchoolInterfaceServiceService(URL wsdlLocation) {
        super(wsdlLocation, WALKSCHOOLINTERFACESERVICESERVICE_QNAME);
    }

    public WalkSchoolInterfaceServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WALKSCHOOLINTERFACESERVICESERVICE_QNAME, features);
    }

    public WalkSchoolInterfaceServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WalkSchoolInterfaceServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WalkSchoolInterfaceService
     */
    @WebEndpoint(name = "walkSchoolInterfaceServicePort")
    public WalkSchoolInterfaceService getWalkSchoolInterfaceServicePort() {
        return super.getPort(new QName("http://www.primeton.com/walkSchoolInterfaceService", "walkSchoolInterfaceServicePort"), WalkSchoolInterfaceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WalkSchoolInterfaceService
     */
    @WebEndpoint(name = "walkSchoolInterfaceServicePort")
    public WalkSchoolInterfaceService getWalkSchoolInterfaceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.primeton.com/walkSchoolInterfaceService", "walkSchoolInterfaceServicePort"), WalkSchoolInterfaceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WALKSCHOOLINTERFACESERVICESERVICE_EXCEPTION!= null) {
            throw WALKSCHOOLINTERFACESERVICESERVICE_EXCEPTION;
        }
        return WALKSCHOOLINTERFACESERVICESERVICE_WSDL_LOCATION;
    }

}
