
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtBursaryAndHighExcellent;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "studentAwardServiceService", targetNamespace = "http://www.primeton.com/studentAwardService", wsdlLocation = "http://fwdt.siso.edu.cn/default/studentAwardService?wsdl")
public class StudentAwardServiceService
    extends Service
{

    private final static URL STUDENTAWARDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STUDENTAWARDSERVICESERVICE_EXCEPTION;
    private final static QName STUDENTAWARDSERVICESERVICE_QNAME = new QName("http://www.primeton.com/studentAwardService", "studentAwardServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fwdt.siso.edu.cn/default/studentAwardService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STUDENTAWARDSERVICESERVICE_WSDL_LOCATION = url;
        STUDENTAWARDSERVICESERVICE_EXCEPTION = e;
    }

    public StudentAwardServiceService() {
        super(__getWsdlLocation(), STUDENTAWARDSERVICESERVICE_QNAME);
    }

    public StudentAwardServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STUDENTAWARDSERVICESERVICE_QNAME, features);
    }

    public StudentAwardServiceService(URL wsdlLocation) {
        super(wsdlLocation, STUDENTAWARDSERVICESERVICE_QNAME);
    }

    public StudentAwardServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STUDENTAWARDSERVICESERVICE_QNAME, features);
    }

    public StudentAwardServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentAwardServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StudentAwardService
     */
    @WebEndpoint(name = "studentAwardServicePort")
    public StudentAwardService getStudentAwardServicePort() {
        return super.getPort(new QName("http://www.primeton.com/studentAwardService", "studentAwardServicePort"), StudentAwardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentAwardService
     */
    @WebEndpoint(name = "studentAwardServicePort")
    public StudentAwardService getStudentAwardServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.primeton.com/studentAwardService", "studentAwardServicePort"), StudentAwardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STUDENTAWARDSERVICESERVICE_EXCEPTION!= null) {
            throw STUDENTAWARDSERVICESERVICE_EXCEPTION;
        }
        return STUDENTAWARDSERVICESERVICE_WSDL_LOCATION;
    }

}
