
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "teacherAwardService", targetNamespace = "http://www.primeton.com/teacherAwardService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TeacherAwardService {


    /**
     * 
     * @param graduate
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "JSONadvancedApplyInfos", targetNamespace = "http://www.primeton.com/teacherAwardService")
    @RequestWrapper(localName = "queryAdvancedApplyInfos", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QueryAdvancedApplyInfos")
    @ResponseWrapper(localName = "queryAdvancedApplyInfosResponse", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QueryAdvancedApplyInfosResponse")
    public String queryAdvancedApplyInfos(
        @WebParam(name = "graduate", targetNamespace = "http://www.primeton.com/teacherAwardService")
        String graduate);

    /**
     * 
     * @param excellYear
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "JSONexcellClassInfo", targetNamespace = "http://www.primeton.com/teacherAwardService")
    @RequestWrapper(localName = "queryExcellClassINfos", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QueryExcellClassINfos")
    @ResponseWrapper(localName = "queryExcellClassINfosResponse", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QueryExcellClassINfosResponse")
    public String queryExcellClassINfos(
        @WebParam(name = "excellYear", targetNamespace = "http://www.primeton.com/teacherAwardService")
        String excellYear);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "JSONSuervisionnevaluationInfos", targetNamespace = "http://www.primeton.com/teacherAwardService")
    @RequestWrapper(localName = "querySupervisionevaluationInfos", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QuerySupervisionevaluationInfos")
    @ResponseWrapper(localName = "querySupervisionevaluationInfosResponse", targetNamespace = "http://www.primeton.com/teacherAwardService", className = "org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward.QuerySupervisionevaluationInfosResponse")
    public String querySupervisionevaluationInfos();

}
