
package org.bureaumanager.bureaumanagerpro.sysConfig.webService.fwdtClassAward;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "teacherAwardServiceService", targetNamespace = "http://www.primeton.com/teacherAwardService", wsdlLocation = "http://fwdt.siso.edu.cn/default/teacherAwardService?wsdl")
public class TeacherAwardServiceService
    extends Service
{

    private final static URL TEACHERAWARDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TEACHERAWARDSERVICESERVICE_EXCEPTION;
    private final static QName TEACHERAWARDSERVICESERVICE_QNAME = new QName("http://www.primeton.com/teacherAwardService", "teacherAwardServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fwdt.siso.edu.cn/default/teacherAwardService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEACHERAWARDSERVICESERVICE_WSDL_LOCATION = url;
        TEACHERAWARDSERVICESERVICE_EXCEPTION = e;
    }

    public TeacherAwardServiceService() {
        super(__getWsdlLocation(), TEACHERAWARDSERVICESERVICE_QNAME);
    }

    public TeacherAwardServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEACHERAWARDSERVICESERVICE_QNAME, features);
    }

    public TeacherAwardServiceService(URL wsdlLocation) {
        super(wsdlLocation, TEACHERAWARDSERVICESERVICE_QNAME);
    }

    public TeacherAwardServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEACHERAWARDSERVICESERVICE_QNAME, features);
    }

    public TeacherAwardServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TeacherAwardServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TeacherAwardService
     */
    @WebEndpoint(name = "teacherAwardServicePort")
    public TeacherAwardService getTeacherAwardServicePort() {
        return super.getPort(new QName("http://www.primeton.com/teacherAwardService", "teacherAwardServicePort"), TeacherAwardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TeacherAwardService
     */
    @WebEndpoint(name = "teacherAwardServicePort")
    public TeacherAwardService getTeacherAwardServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.primeton.com/teacherAwardService", "teacherAwardServicePort"), TeacherAwardService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEACHERAWARDSERVICESERVICE_EXCEPTION!= null) {
            throw TEACHERAWARDSERVICESERVICE_EXCEPTION;
        }
        return TEACHERAWARDSERVICESERVICE_WSDL_LOCATION;
    }

}
